# Travis configuration.  Build the simulator and run its tests.

language: rust
script:
    - cd sim; cargo build --release
    - cd sim; cargo run --release -- runall
    - cd sim; cargo run --release --features sig-rsa -- runall
